_target_: drugprot.models.entity_marker_baseline.EntityMarkerBaseline

transformer: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract
lr: 3e-5
finetune_lr: 1e-5
loss: bce
tune_thresholds: false
use_doc_context: false
use_cls: true
use_starts: false
use_ends: false
mark_with_special_tokens: false
blind_entities: false
